# ################################################################################################# #
# 此文件是【开发环境】的配置文件，必须在主配置中通过spring.profiles.active激活此配置，此文件中的各配置才会生效 #
# ################################################################################################# #

# 服务器的配置
server:
  # 服务占用的端口
  port: 9527
  
# Spring的配置
spring:
  # 数据源的配置
  datasource:
    # 连接数据库的URL
    url: jdbc:mysql://localhost:3306/furniture_store?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    # 数据库用户名
    username: root
    # 数据库密码
    password: 123456
    # Druid连接池的配置
    druid:
      # 配置数据库连接池初始化连接数
      initial-size: 5
      # 配置数据库连接池最大连接数
      max-active: 20

# 将com.example.furniture下的日志级别设置为trace，默认为debug
# 日志配置
logging:
  # 显示级别
  level:
    # 某根包（配置将应用于此包及子孙包）的显示级别
    com.example.furniture: trace